"""
Report generation module.

This module is responsible for converting alerts into report files.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from suspicious_process_detector.models import ProcessAlert


class JsonReporter:
    """
    Saves scan results as a JSON report.
    """

    def save(self, alerts: list[ProcessAlert], output_path: str | Path) -> Path:
        """
        Save alerts to a JSON file.

        Args:
            alerts: Alerts generated by the analyzer.
            output_path: Destination path for the JSON report.

        Returns:
            Path: Final saved report path.
        """
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        payload = self._build_payload(alerts)

        with path.open("w", encoding="utf-8") as report_file:
            json.dump(payload, report_file, indent=2, ensure_ascii=False)

        return path

    def _build_payload(self, alerts: list[ProcessAlert]) -> dict:
        """
        Build the JSON report payload.

        Args:
            alerts: Alerts to include in the report.

        Returns:
            dict: JSON-serializable report payload.
        """
        return {
            "tool": "suspicious-process-detector",
            "generated_at": self._utc_now(),
            "total_alerts": len(alerts),
            "alerts": [alert.to_dict() for alert in alerts],
        }

    @staticmethod
    def _utc_now() -> str:
        """
        Return current UTC time in ISO 8601 format.

        Returns:
            str: UTC timestamp.
        """
        return datetime.now(timezone.utc).isoformat()